### ISSUE TITLE
Messages show up in channel out of order

### ISSUE THREAD

**Issue by RyanHoldren** [maricn/logback-slack-appender#1]
It seems that the messages I'm logging some times show up in Slack out of order. Is this a problem you've seen before?

My logback config looks something like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>

  <appender name="slackAppender" class="com.github.maricn.logback.SlackAppender">
      <token>xxxx-xxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxx</token>
      <channel>#xxxxxxxx</channel>
      <username>${HOSTNAME}</username>
  </appender>

  <appender name="asyncSlackAppender" class="ch.qos.logback.classic.AsyncAppender">
      <appender-ref ref="slackAppender" />
  </appender>

  <logger name="slackLogger">
    <appender-ref ref="asyncSlackAppender" />
  </logger>

  <root>
    <level value="ALL" />
    <appender-ref ref="slackLogger" />
  </root>

</configuration>
```

**Comment by maricn** [comment]
Hi @RyanHoldren,
No, I haven't faced that issue. Have you definitely concluded that the messages are out of order? Logback config seems fine.
AsyncAppender should keep ordering, it can only **discard** some messages of lower priority if it's queue is full.
It may be due to networking if you're having a lot of messages rapidly sent.
